### ISSUE TITLE
navigationbar item won't be hidden

### ISSUE THREAD

**Issue by dreamgo** [JoeFryer/JDFPeekaboo#12]
First, thanks for your great job. 
I add a segmentController and a right item bar button to navigationbar. Everything works well except these two items I add won't be hidden.
Any idea to fix it?

![untitled](https://cloud.githubusercontent.com/assets/6346870/7404560/bd1e77f2-eeb2-11e4-9cf1-0fca2a3c1b0a.png)

Thanks!

**Comment by JoeFryer** [comment]
Hi @dreamgo - no problem!

Have you tried adding them to the `topViewItems` property?

**Comment by dreamgo** [comment]
Thanks for your reply!
It works well on navigation title view.
But I have no idea how to work on UIBarButtonItem button.
 Can you give me an example?
Thanks!

**Comment by dreamgo** [comment]
What I tried to do is add NSArray *itemArr = [[NSArray alloc] initWithObjects:
                        self.navigationItem.titleView,
                        self.navigationItem.leftBarButtonItem.customView, nil] to topViewItems.
but it still doesn't work on barbutton items.

**Comment by dreamgo** [comment]
And what's more, when I add titleView to topViewItems, the titleView can't be disappear immediately can I push to subView.

**Comment by TuWei1992** [comment]
same problem with me...

**Comment by TuWei1992** [comment]
but fixed, use `topViewItems` ☺

**Comment by TuWei1992** [comment]
But when I go back to the last view, leftbarbuttonItem hides no fade effect.
