### ISSUE TITLE
Wrong bottom bar positioning

### ISSUE THREAD

**Issue by filipandrei87** [JoeFryer/JDFPeekaboo#14]
Line 222 calculation is wrong. It should use bottom bar height instead of top bar height:

```
    bottomBarFrame.origin.y = defaultBottomViewY + topBarHeight;
```

should be

```
    bottomBarFrame.origin.y = defaultBottomViewY + self.bottomBarDefaultHeight;
```

**Comment by JoeFryer** [comment]
Hi @filipandrei87,

Thanks for pointing this out - I'll get it fixed!

**Comment by JoeFryer** [comment]
Thanks for reporting @filipandrei87 - this has now been fixed. Will be in the next release.
