### ISSUE TITLE
Doesn't work if UIScrollView is a subview of UIViewController.view

### ISSUE THREAD

**Issue by ianhirschfeld** [JoeFryer/JDFPeekaboo#15]
Example: I have a UIViewController with a UITableView inside of it. Setting the UITableView subview as the scrollable view doesn't move the parent view with it.

This is different from the "black bar" you have in the readme. In this case, that black bar is the UIViewController.view even though UIViewController is set to extend to edges.

![](http://cl.ly/image/1x1U052H0A1z/Screen%20Recording%202015-10-16%20at%2004.08%20PM.gif)

**Comment by JoeFryer** [comment]
So, the black area you see is the view controller's view (its colour is black)? And your table view doesn't extend underneath the navigation bar? That's what needs to happen - your table view needs to extend underneath the navigation bar as well.

**Comment by ianhirschfeld** [comment]
It is the ViewController's view but even set to background color transparent it's the same effect. I also tried this in the demo app you provide and it has the same affect. Here is my initializer code:

``` objc
self.scrollCoordinator = [[JDFPeekabooCoordinator alloc] init];
self.scrollCoordinator.scrollView = home_list; // This is the tableView which is a subview of ViewController.view
self.scrollCoordinator.topView = self.navigationController.navigationBar;
```

In my storyboard the tableView has it's top constraint linked to the Top Layout Guide.

**Comment by JoeFryer** [comment]
JDFPeekaboo doesn't alter the frame of the scrollView - it works by changing the scrollView's contentInset. Therefore, the scrollView needs to extend to the top of the screen, i.e. underneath the navigationBar, so you don't want to use the Top Layout Guide (using this will position your table view to start at the bottom of the navigation bar). You want to position your table view to start at the top of your view controller's view.

**Comment by ianhirschfeld** [comment]
Alright I went back and checked your `CustomViewExampleTableViewController` storyboard since that is doing what I want to do. I found my mistake, I had this in my ViewController: `self.automaticallyAdjustsScrollViewInsets = false;`. I removed that and all is well now! Thanks for your help and for this Pod! :D

**Comment by JoeFryer** [comment]
Ah I see. No problem - I'm glad you like it! 😄

**Comment by Alkalouti** [comment]
How i can use it when uitalbleview auto layout please advice
