### ISSUE TITLE
Bottom contentInset being ignored even when bottomView is not set

### ISSUE THREAD

**Issue by thomasgpeng** [JoeFryer/JDFPeekaboo#18]
It looks like `UIScrollViewDelegate` method `scrollViewDidScroll` is wiping out `contentInset.bottom` even if `self.bottomView` isn't set (which it wouldn't be if we only wanted the top bar to hide).  This is a problem for those of us who want a non-zero `contentInset.bottom` so we can have a translucent bottom bar that doesn't block the last row of the scrollView.  Any chance we can get this fixed?  I can submit a pull request if you guys like.

**Comment by JoeFryer** [comment]
Thanks @thomasgpeng - that definitely needs fixing.

You're very welcome to submit a pull request if you like - that would be much appreciated! Otherwise you can leave this open and I'll fix it when I next have time to look at it.
