### ISSUE TITLE
Does not works for custom bar items

### ISSUE THREAD

**Issue by yasirmturk** [JoeFryer/JDFPeekaboo#5]
when using `[[UIBarButtonItem alloc] initWithCustomView:rightBtn];` nothing is dimmed

**Comment by yasirmturk** [comment]
![img_0223](https://cloud.githubusercontent.com/assets/306691/6366355/3ba199a0-bce6-11e4-8724-6184a246285f.PNG)

**Comment by JoeFryer** [comment]
Thanks for reporting @yasirmturk - I'll take a look.

**Comment by JoeFryer** [comment]
Hi @yasirmturk - I haven't been able to reproduce this. Could you provide some more info about your setup?

**Comment by yasirmturk** [comment]
initialize a `UIButton` with cutom type and set a `UIImage` to it ..then pass it to the custom view of `UIBarButtonItem`

**Comment by JoeFryer** [comment]
Have you tried adding the `UIButton` to `JDFPeekaboo`'s `topViewItems`?

**Comment by yasirmturk** [comment]
am i supposed to do that for every custom view added to `UINavigationBar`

**Comment by JoeFryer** [comment]
Yep
