### ISSUE TITLE
Does not works for landscape

### ISSUE THREAD

**Issue by yasirmturk** [JoeFryer/JDFPeekaboo#6]
scrolling up should hide the bars completely in landscape
scrolling down should not add white space
![img_0224](https://cloud.githubusercontent.com/assets/306691/6366358/62abe244-bce6-11e4-8e52-a6a26568b63c.PNG)
![img_0225](https://cloud.githubusercontent.com/assets/306691/6366359/64d67746-bce6-11e4-87af-9c46cc629ee0.PNG)

**Comment by JoeFryer** [comment]
Thanks for reporting @yasirmturk - I'll take a look.

**Comment by JoeFryer** [comment]
Hey @yasirmturk - I've [made some changes](https://github.com/JoeFryer/JDFPeekaboo/commit/d4117dbbf17272f98a49ed3ad60d5b0fc76fec15) to help with this, perhaps you could have a look and tell me what you think? Cheers.
