### ISSUE TITLE
Won't stop when pushing a new viewController

### ISSUE THREAD

**Issue by mariusglauer** [JoeFryer/JDFPeekaboo#7]
When you push a new view controller via your navigationController, the JDFPeekaboo will unexpectedly continue to work.
I used these 3 lines in the destination view controller's `viewDidAppear` method to bypass this behaviour:

``` objective-c
CGRect frame = self.navigationController.navigationBar.frame;
frame.origin.y = 20.0;
[self.navigationController.navigationBar setFrame:frame]; 
```

**Comment by JoeFryer** [comment]
I've just [pushed a fix](https://github.com/JoeFryer/JDFPeekaboo/commit/b3c04140c8b1d133d6a2ca9f6e84088e280c6080) for this.

I've added some methods for disabling/re-enabling `JDFPeekaboo` that you can use when you push a new view controller. Have a look at the demo project for example (I disable in `-viewWillDisappear:` and re-enable in `-viewDidAppear:`. 

Let me know what you think.

**Comment by mariusglauer** [comment]
Very nice @JoeFryer, thanks!
